name = "TarIterators"
uuid = "06456b94-f2fb-4c2e-911f-0795f0d2fb0a"
authors = ["Klaus Crusius <klaus.crusius@web.de>"]
version = "0.2.1"

[deps]
BoundedStreams = "819c7365-da23-433e-86d1-f9a07e67aad6"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
Tar = "1"
BoundedStreams = "0.2.1"
julia = "1"

[extras]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[targets]
test = ["Test", "CodecZlib", "TranscodingStreams"]
